### Introducción a Numpy - Librería de Python para realizar cálculos numéricos en Python

#### Primero tenemos que importar la libreria usando `import`. Para evitar escribir `numpy` cada vez usamos una función que nos permite asignarle un alias `as`:

In [1]:
import numpy as np

#### Ahora tenemos acceso a todas las funciones disponibles en  `numpy` tipeando `np.name_of_function`.  Por ejemplo, la operación `1 + 1` en Python se puede realizar en `numpy` de la siguente manera:

In [25]:
np.add(1,1)

2

##### Aunque no parezca muy útil, estas operaciones pueden ser mucho más rápidas en `numpy` que en Python cuando se usan muchos números. 

#### Para acceder a la documentación que explica cómo se usa una función, cuáles son sus parámetros de entrada y de salida, hay que poner `Shift+Tab` después del nombre de la función

In [26]:
np.add

SyntaxError: ignored

#### Por default se muestra el resultado de la función u operación al ejecutar la celda

> Bloque con sangría



In [4]:
np.add(2,3)

5

#### Si se va a reutilizar el resultado después se puede asignar el resultado a una variable

In [5]:
a = np.add(2,3)

#### El contenido de esta variable se puede mostrar en cualquier momento tipieando el nombre de la variable en una nueva celda

In [6]:
a

5

#### Uno de los conceptos más poderosos en numpy son los `arrays`  (o arreglos) que son equivalentes a listas de números. Para declarar un array de numpy:

In [7]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### La mayoría de las funciones y operaciones definidas en numpy pueden aplicarse a arrays. Por ejemplo, con la operación de recién:

In [8]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

np.add(arr1, arr2)

array([ 4,  6,  8, 10])

#### Ejercicio: Definimos un array con un elemento más (arr3) y vean qué pasa si queremos hacer la suma arr1+arr3. Normalmente los arrays tienene que tener las mismas dimensiones 

In [12]:
arr3 = np.array([1,2,3,4])

In [13]:
arr1 + arr3

array([2, 4, 6, 8])

1-Generar dos arreglos de tipo entero.
2-Sumarlos entre ellos.
3-Sumar 2 a cada elemento del arreglo.


#### Ejercicio: qué pasa si hacemos arr1+1?

In [14]:
arr1 + 1

array([2, 3, 4, 5])

In [15]:
 np.add (arr1, 2) 


array([3, 4, 5, 6])

#### Los arreglos se pueden recortar. Nos podemos quedar con subsets del array usando la siguiente notación`[start:end:stride]`. Veamos un ejemplo:

In [16]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(arr[5])
print(arr[5:])
print(arr[:5])
print(arr[::2])

5
[ 5  6  7  8  9 10 11 12 13 14 15]
[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14]


##### Experimenten jugando con los índices para entender el significado de start, end y stride. Qué pasa si no especifican el start? Qué valor usa numpy como default? NOTA: el primer índice en numpy es `0`, la misma convención se usa en las listas de Python.

#### Los arreglos de Numpy arrays pueden tener múltiples dimensiones. Por ejemplo, para definir un `column` array: 

In [17]:
np.array([[1,2,3,4,5,6,7,8,9]])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [18]:
arre = np.array([1,2,3,4,5,6,7,8,9])
print(arre[3])
print(arre[7:])

4
[8 9]


#### Para visualizar la forma o dimensiones del arreglo de numpy hay que agregar el sufijo`.shape`

In [19]:
print(np.array([1,2,3,4,5,6,7,8,9]).shape)
print(np.array([[1,2,3,4,5,6,7,8,9]]).shape)

(9,)
(1, 9)


##### Para definir una rreglo de dos dimensiones:

In [20]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
print(np.array([[1,2,3,4],[5,6,7,8]]).shape)

(2, 4)


#### Se pueden reordenar los datos del arreglo a diferentes formas con la función `reshape`:

In [22]:
np.array([1,2,3,4,5,6,7,8]).reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Definan un arreglo de 3 dimensiones con la forma  (5,3,3)

In [23]:

practica = np.linspace(5, 3, 3)
print(practica)


[5. 4. 3.]


#### Creen otro y usen la función de numpy para sumar ambos arrays:

In [24]:
arre = np.array([10,20,30],[40,50,60],[70,80,90])
practica + arre

TypeError: ignored

### Cómo extraer items que satisfacen una cierta condición en un array 1D?

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 


####  Extraer los números impares de arr 

In [ ]:
arr[arr % 2 == 1]

In [ ]:
x = np.array([1, 2, 3, 4, 5])


In [ ]:
x = np.array([1, 2, 3, 4, 5])
x < 3  # less than



### Operador :	Función equivalente		
* "!="	:	np.not_equal
* "<"	:	np.less		
* "<=" :	np.less_equal
* ">"	:	np.greater	
* ">=" :	np.greater_equal

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

In [ ]:
x < 6


In [ ]:
# Cuántos valores son menores a  6?
np.count_nonzero(x < 6)

In [ ]:
# Cuántos valores son menores a  6 en cada fila?
np.sum(x < 6, axis=1)

In [ ]:
# Son todos los valores en cada fila menores a 8?
np.all(x < 8, axis=1)

### Mas ejercicios
https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html
    